@extends('layouts.app')
@section('title')
@endsection
@section('preloader')
@endsection
@section('css')
@endsection
@section('csspage')
@endsection
@section('parametreactive')
@endsection
@section('salleactive')
@endsection
@section('HeaderPage')
@endsection
@section('ContenuPage')
@endsection
@section('scripts')
@endsection
@section('scriptpage')
@endsection
